services:
  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local